spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/pluxity-3d-interior
    username: pluxity
    password: pluxity123!@#
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database-platform: org.hibernate.dialect.H2Dialect